# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            github.client:
                base_uri: 'https://api.github.com/'
                auth_bearer: '%env(KANBANBOT_TOKEN)%'
                headers:
                    Accept: 'application/vnd.github.v3+json'
                retry_failed:
                    http_codes: [403, 408, 423, 425, 429, 500, 502, 503, 504, 507, 510]
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 8000

    webhook:
        routing:
            github:
                service: App\Shared\Infrastructure\Webhook\GithubWebhookParser

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
