
name: KanbanBot Production CICD

concurrency:
  group: kanbanbot-${{ github.ref }}

on:
  release:
    types: [released]
  pull_request:
    branches:
      - 'feat/production-workflow'

jobs:

  kanbanbot-production:
    name: Trigger Production CICD
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - name: Get tag
        shell: bash
        id: get_tag
        run: echo TAG=$(echo $GITHUB_REF | cut -d / -f 3) >> $GITHUB_OUTPUT

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.KANBANBOT_CD_PAT }}
          repository: ${{ secrets.KANBANBOT_CD_REPOSITORY }}
          event-type: production_deployment
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "tag": "${{ steps.get_tag.outputs.TAG }}"}'
