name: Need second review

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    -  uses: tspascoal/get-user-teams-membership@v2
       id: checkUserMember
       with:
         organization: PrestaShop
         username: ${{ github.actor }}
         team: 'committers'
         GITHUB_TOKEN: ${{ secrets.GHPROJECT_TOKEN }}
    - if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
      run: echo "yes"

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        composer self-update --2.2
        composer install --no-interaction

    - name: Test PHP
      env:
        GITHUB_TOKEN: ${{ secrets.GHPROJECT_TOKEN }}
        PR_ID: 32162 # ${{ github.event.pull_request.node_id }}
      run:
        php bin/console kanbanbot:need-second-review